# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hey, it's Ray.
email: rayzeller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Oh hey.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rayzeller.com" # the base hostname & protocol for your site
twitter_username: rayzeller
github_username:  rayzeller

# Build settings
markdown: kramdown
